from pydantic import BaseModel, Field, validator
from datetime import datetime
from typing import Optional, Dict, Any
from enum import Enum
from uuid import uuid4
import ipaddress

# Severity levels for alerts
class SeverityLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

# Supported alert types
class AlertType(str, Enum):
    BRUTE_FORCE = "Brute Force"
    MALWARE = "Malware"
    PHISHING = "Phishing"
    DDOS = "DDoS"
    UNAUTHORIZED_ACCESS = "Unauthorized Access"
    RANSOMWARE = "Ransomware"

# Risk levels generated by the risk engine
class RiskLevel(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"

# Incoming raw alert from SIEM
class Alert(BaseModel):
    alert_type: AlertType = Field(..., example="Brute Force")
    source_ip: str = Field(..., example="192.168.1.100")
    severity: SeverityLevel = Field(..., example="high")
    timestamp: datetime = Field(..., example="2026-06-22T10:00:00Z")
    description: Optional[str] = Field(
        default=None,
        example="Multiple failed login attempts detected."
    )
    destination_ip: Optional[str] = Field(
        default=None,
        example="10.0.0.5"
    )
    port: Optional[int] = Field(
        default=None,
        example=22,
        ge=1,
        le=65535
    )

    @validator("source_ip", "destination_ip")
    def validate_ip(cls, value):
        """
        Validate IPv4 and IPv6 addresses.
        """
        if value is None:
            return value
        try:
            ipaddress.ip_address(value)
        except ValueError:
            raise ValueError("Invalid IP address format")
        return value

# Standardized alert format used internally by SOAR
class NormalizedAlert(BaseModel):
    alert_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for each alert"
    )
    alert_type: str
    source_ip: str
    severity: str
    timestamp: datetime
    normalized_timestamp: str
    description: Optional[str] = None
    destination_ip: Optional[str] = None
    port: Optional[int] = None
    risk_score: Optional[float] = None
    risk_level: Optional[RiskLevel] = None
    action_taken: Optional[str] = None
    enrichment_data: Optional[Dict[str, Any]] = None  # ✅ Added

    class Config:
        from_attributes = True  # ✅ Pydantic v2 compatible